#!/usr/bin/env zsh

progName=$0

() {

    countIntermediateFiles() {

        benchsdir=$1

        print -lr '' 'Number of .c files in '"$benchsdir:"
        find $benchsdir -maxdepth 1 -name "*.c" | wc -l

        print -lr '' 'Number of descriptors generated:'
        find $benchsdir -wholename "*.d/descriptor" | wc -l

        print -lr '' 'Number of constraints generated by Konstrain'"'"'s big-arr strategy:'
        find $benchsdir -wholename "*.d/constraint_big-arr" | wc -l

        print -lr '' 'Number of .c files generated by Jotai.cpp with a main() entry point:'
        find $benchsdir -wholename "*.d/*.c" | wc -l

        print -lr '' 'Number of binaries successfully compiled by clang with -O0:'
        find $benchsdir -wholename "*.d/*O0" | wc -l

        print -lr '' 'Number of .map files generated by cfggrind_asmmap:'
        find $benchsdir -wholename "*.d/*.map" | wc -l

        print -lr '' 'Number of .cfg files generated by valgrind with --tool=cfggrind:'
        find $benchsdir -wholename "*.d/*.cfg" | wc -l

        print -lr '' 'Number of .info files with stats produced by cfggrind_info:'
        find $benchsdir -wholename "*.d/*.info" | wc -l

    }

    # ---

    countIntermediateFiles $1

} "$@"

setopt nonomatch
rm -f vgcore*